### ISSUE TITLE
"Choose books" broken

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#860]
Recently the "Choose Books" area of the Basic tab has stopped working. In particular, if I try to _type_ in that area I get the following error.

```
Traceback (most recent call last):
  File "D:/Documents\github\ptx2pdf\python\scripts/../lib/ptxprint/gtkview.py", line 1381, in onBkLstKeyPressed
    if self.blInitValue != self.get('ecb_booklist'):
AttributeError: 'GtkViewModel' object has no attribute 'blInitValue'


PTXprint Version 2.3.6-g9108d8e9
```

This has worked fine until recently. bfcb1c6a1a7ddb56d17e4c36afb318df62e690ca is the first bad commit

**Comment by markpenny** [comment]
Thanks for the heads-up. My bad. It has been fixed and will be in the next release, hopefully in a few minutes.

**Comment by mnjames** [comment]
Confirmed. Thank you.
