### ISSUE TITLE
Archiving Fails for Bible Modules

### ISSUE THREAD

**Issue by mnjames** [sillsdev/ptx2pdf#739]
If you choose a Bible Module and then Create Archive, you get this error (and no archive)

```
Please send to: ptxprint_support@sil.org



Traceback (most recent call last):
  File "ptxprint\gtkview.py", line 3124, in onCreateZipArchiveClicked
  File "ptxprint\view.py", line 1491, in createArchive
  File "ptxprint\view.py", line 1530, in _archiveAdd
  File "ptxprint\view.py", line 1335, in _getArchiveFiles
TypeError: __init__() missing 1 required positional argument: 'model'

<class 'TypeError'>: __init__() missing 1 required positional argument: 'model'


PTXprint Version 2.2.25
```

**Comment by mnjames** [comment]
Working correctly in 2.2.26. Thank you.
